FROM node:12

WORKDIR /usr/unitrade-service

COPY package.json .
COPY yarn.lock .

RUN yarn

COPY . .

ENV DEBUG="unitrade-service*"
ENV ACCOUNT_ADDRESS=${ACCOUNT_ADDRESS}
ENV ACCOUNT_PRIVATE_KEY=${ACCOUNT_PRIVATE_KEY}
ENV PROVIDER_URI=${PROVIDER_URI}
ENV UNITRADE_ADDRESS=${UNITRADE_ADDRESS}
ENV UNISWAP_ROUTER_ADDRESS=${UNISWAP_ROUTER_ADDRESS}
ENV UNISWAP_FACTORY_ADDRESS=${UNISWAP_FACTORY_ADDRESS}
ENV DEFAULT_GAS_LIMIT=${DEFAULT_GAS_LIMIT}

CMD ["yarn", "main"]